### ISSUE TITLE
Porty doesn't work on Spigot 1.9

### ISSUE THREAD

**Issue by helptiger** [Moehritz/Porty#15]
[18:28:29 ERROR]: Could not pass event PlayerMoveEvent to Porty-Bukkit v1.1
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:579) [spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at net.minecraft.server.v1_9_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at net.minecraft.server.v1_9_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-86016ba-94ba824]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at me.moehritz.porty.internal.io.CallbackSender.sendCallback(CallbackSender.java:17) ~[?:?]
at me.moehritz.porty.internal.TeleportTimer$TeleportTimerRun.cancel(TeleportTimer.java:55) ~[?:?]
at me.moehritz.porty.internal.PlayerListener.onMove(PlayerListener.java:21) ~[?:?]
at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-86016ba-94ba824]
... 15 more

**Comment by Moehritz** [comment]
https://www.spigotmc.org/resources/porty.454/update?update=74660

Thanks for telling me! (Better late than never I guess?)
